export enum DataType {
  STRING = "string",
  NUMBER = "number",
  BOOLEAN = "boolean",
  ARRAY = "array",
  OBJECT = "object",
}

export enum NodeType {
  LLM = "LLM",
  DOCUMENT_SPLITTER = "DOCUMENT_SPLITTER",
  TEXT_EMBEDDING = "TEXT_EMBEDDING",
  VECTOR_INSERT = "VECTOR_INSERT",
  VECTOR_SEARCH = "VECTOR_SEARCH",
  VECTOR_UPDATE = "VECTOR_UPDATE",
  VECTOR_DELETE = "VECTOR_DELETE",
  FOR_EACH = "FOR_EACH",
  UPDATE_VARIABLE = "UPDATE_VARIABLE",
  CONDITION = "CONDITION",
}

export enum ValidationErrorCode {
  // Schema validation errors
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_TYPE = "INVALID_TYPE",
  INVALID_FORMAT = "INVALID_FORMAT",
  INVALID_VALUE = "INVALID_VALUE",

  // Flow structure errors
  DUPLICATE_NODE_ID = "DUPLICATE_NODE_ID",
  DUPLICATE_VARIABLE_ID = "DUPLICATE_VARIABLE_ID",
  INVALID_NODE_TYPE = "INVALID_NODE_TYPE",

  // Dependency errors
  CIRCULAR_DEPENDENCY = "CIRCULAR_DEPENDENCY",
  MISSING_DEPENDENCY = "MISSING_DEPENDENCY",
  INVALID_VARIABLE_REFERENCE = "INVALID_VARIABLE_REFERENCE",
  FORWARD_REFERENCE = "FORWARD_REFERENCE",

  // Provider errors
  UNKNOWN_PROVIDER = "UNKNOWN_PROVIDER",
  MISSING_PROVIDER_CONFIG = "MISSING_PROVIDER_CONFIG",

  // Output schema errors
  INVALID_OUTPUT_SCHEMA = "INVALID_OUTPUT_SCHEMA",
  MISSING_OUTPUT_PROPERTY = "MISSING_OUTPUT_PROPERTY",
}
